<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_View</name>
   <tag></tag>
   <elementGuidId>c7b2e053-f5bd-4eef-95a2-8d6f6cda9dbd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='member-action-button-0']/div/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.color-blue-1.d-flex.align-items-center.justify-content-start.rounded.px-3.py-2.mr-1</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=row[name=&quot;Test Guest testguest75306 testguest321@allfreemail.net guest Active View&quot;i] >> internal:role=link</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>3814e99b-ee90-495f-b632-45577e4f5db2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>color-blue-1 d-flex align-items-center justify-content-start rounded px-3 py-2 mr-1</value>
      <webElementGuid>0dee0166-b475-4af5-b479-b0ad84e7ec1d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/dashboard/members/22</value>
      <webElementGuid>6fe5d2de-5aa6-4eff-9185-744e43e01adc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>View</value>
      <webElementGuid>9cd43861-7a9e-48ce-bebd-6fd7f3009760</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;member-action-button-0&quot;)/div[@class=&quot;d-flex flex-row align-items-start justify-content-end flex-wrap&quot;]/a[@class=&quot;color-blue-1 d-flex align-items-center justify-content-start rounded px-3 py-2 mr-1&quot;]</value>
      <webElementGuid>28608ad0-3735-452d-b84c-455f72fdb999</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='member-action-button-0']/div/a</value>
      <webElementGuid>5837fa75-991d-494b-bf9e-1a4eb27242da</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'View')]</value>
      <webElementGuid>5536475d-ad2f-4bd9-9698-93338b7c128b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Active'])[1]/following::a[1]</value>
      <webElementGuid>86835d44-8473-4d0e-927f-19f4b391e577</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='guest'])[1]/following::a[1]</value>
      <webElementGuid>87fb5d53-5745-47d6-bda7-3e0269ad62d9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Guest Test'])[1]/preceding::a[1]</value>
      <webElementGuid>2800d7d7-5388-4756-b5a1-9aef8790c377</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='guesttest95785'])[1]/preceding::a[1]</value>
      <webElementGuid>4994e228-87a3-46ad-8074-5ca4639ec8e9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='View']/parent::*</value>
      <webElementGuid>a2be28ba-4ccc-4b1a-8dfe-d0ffc8f22063</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/dashboard/members/22')]</value>
      <webElementGuid>ea10f15f-d774-41e4-b539-b7bde8d8aae9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[6]/div/div/a</value>
      <webElementGuid>337a156b-a981-4861-9970-d367d585a4f0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/dashboard/members/22' and (text() = 'View' or . = 'View')]</value>
      <webElementGuid>d896e55c-365a-4c29-953b-0b610218d2a9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
