<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>b_You have one more attempt before your account is locked</name>
   <tag></tag>
   <elementGuidId>5226913a-2c79-41f0-a196-8879299a0045</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#flash_alert</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//b[@id='flash_alert']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;You have one more attempt before your account is locked.&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>b</value>
      <webElementGuid>4dfecc26-d890-4baa-a3f4-b4ee4f6fb3bc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>flash_alert</value>
      <webElementGuid>851266ae-ad3f-41f2-b3b5-cccca61475e6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>You have one more attempt before your account is locked.</value>
      <webElementGuid>7d1c6db2-396d-4d58-a4a3-c98a8c122554</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;flash_alert&quot;)</value>
      <webElementGuid>fe6e8bfa-443f-46c2-8788-1cdef5ed82a9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//b[@id='flash_alert']</value>
      <webElementGuid>8b800dad-0510-4554-b64f-3b6fe7dbf71b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='notify']/b</value>
      <webElementGuid>03d7c194-2d83-41d2-b4ab-72e1222fd7b9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Login'])[1]/preceding::b[1]</value>
      <webElementGuid>d8120007-645a-4842-81df-8cb74d7a8e6f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Username'])[1]/preceding::b[1]</value>
      <webElementGuid>4b1dbf44-b6fd-4ebf-bba2-1af787dbe084</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='You have one more attempt before your account is locked.']/parent::*</value>
      <webElementGuid>c7d6ec5c-bd80-4585-b490-7020ed891ef0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//b</value>
      <webElementGuid>a51f7a32-e576-4df1-9a3e-d918c8a302f2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//b[@id = 'flash_alert' and (text() = 'You have one more attempt before your account is locked.' or . = 'You have one more attempt before your account is locked.')]</value>
      <webElementGuid>e60e6f7c-f504-4842-86e4-72403f23b8f0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
