<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_View_1</name>
   <tag></tag>
   <elementGuidId>0530aa3d-b3c2-4781-909d-d6f6d52170d5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='member-action-button-0']/div/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.color-blue-1.d-flex.align-items-center.justify-content-start.rounded.px-3.py-2.mr-1</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=row[name=&quot;Simpul Guest simpulguest58991 simpulguest111@allfreemail.net guest Active View&quot;i] >> internal:role=link</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>6999ab9d-58b1-4903-97ad-c9699d45e091</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>color-blue-1 d-flex align-items-center justify-content-start rounded px-3 py-2 mr-1</value>
      <webElementGuid>21687e0a-1336-4f92-8686-5995ff8f07dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/dashboard/members/23</value>
      <webElementGuid>636ebf29-2708-4f1e-ac32-43df337c4d00</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>View</value>
      <webElementGuid>24b24643-3348-4c7d-a951-4ee73407e2dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;member-action-button-0&quot;)/div[@class=&quot;d-flex flex-row align-items-start justify-content-end flex-wrap&quot;]/a[@class=&quot;color-blue-1 d-flex align-items-center justify-content-start rounded px-3 py-2 mr-1&quot;]</value>
      <webElementGuid>82624487-5e0d-4191-b0f2-1f77be50bc2a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='member-action-button-0']/div/a</value>
      <webElementGuid>cfcede97-e39a-48d5-9aab-36a5f9d0000b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'View')]</value>
      <webElementGuid>ab1f4310-4dc5-44ef-a81d-2fd5c24910c0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Active'])[1]/following::a[1]</value>
      <webElementGuid>f2c56bc3-d472-49d2-93ce-98ac73998535</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='guest'])[1]/following::a[1]</value>
      <webElementGuid>36984478-81e3-467f-8c74-0dcb6dd9155d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Test Guest'])[1]/preceding::a[1]</value>
      <webElementGuid>992c9d68-5765-4d70-8263-a87ead7b7b5b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='testguest75306'])[1]/preceding::a[1]</value>
      <webElementGuid>0ca741e6-fce7-4018-a2e5-007a467af1bf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='View']/parent::*</value>
      <webElementGuid>5bf7f34c-ff11-4a76-af46-15b7b918d0c1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/dashboard/members/23')]</value>
      <webElementGuid>bade609f-8418-4e45-9c37-f7092b8252f1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[6]/div/div/a</value>
      <webElementGuid>f127ebb9-e6de-4e18-804b-43fa13e792bf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/dashboard/members/23' and (text() = 'View' or . = 'View')]</value>
      <webElementGuid>0373fa34-ca82-4f77-8692-1fc0970217d4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
