<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Search Help Here_v-skeleton-loader__tex_6c88c5</name>
   <tag></tag>
   <elementGuidId>3b3bff11-6255-46fd-9ae5-ba103e09206d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//form[@id='new_task']/div[6]/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.tokenfield.form-control.focus</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>.tokenfield</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>8f2dfc18-b261-4a83-b240-8849c62142a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>tokenfield form-control focus</value>
      <webElementGuid>7ecc4fb7-26f7-4ac5-9e09-97068c1c8ffc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;new_task&quot;)/div[6]/div[@class=&quot;tokenfield form-control focus&quot;]</value>
      <webElementGuid>88df8673-a4f1-48f7-8a4c-cd39a9cf4a36</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='new_task']/div[6]/div</value>
      <webElementGuid>473bae47-1f19-4f68-aa02-77a45f5dcda5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Assign to case'])[1]/following::div[2]</value>
      <webElementGuid>7420e352-4bd8-4b45-8d98-7dc27ba9fc5b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Due date'])[1]/following::div[3]</value>
      <webElementGuid>82eb7b6c-c584-471f-a3a0-40f067b8cb44</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div</value>
      <webElementGuid>d204f170-eb3c-42fd-bc30-7189c66d6acc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/main/div/div/div[2]/div/div[2]/div/div[2]/div/div/div/div[6]/div/div</value>
      <webElementGuid>582c462f-580f-4365-af92-8be3204fde53</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div/div</value>
      <webElementGuid>5fd120fb-5de2-4ec8-aa82-20e00f6657af</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
