<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Clients_query</name>
   <tag></tag>
   <elementGuidId>9bcf4978-9b42-4d87-a280-15bd3049ac76</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#apply-form > #query</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//input[@id='query'])[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;Search clients by name, ssn, a-number, or phone number&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>956005aa-bb01-4322-96b3-7a68e05c3b31</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>13f624f8-eda5-471b-8097-8145ed1413b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>query</value>
      <webElementGuid>789c7587-c693-4d28-aa5a-3df369291374</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>query</value>
      <webElementGuid>a2b7c982-80b0-45a3-992c-bbc235a37515</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>68334529-a29b-4919-86f9-820163a55e62</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Search clients by name, ssn, a-number, or phone number</value>
      <webElementGuid>6bda60c6-8f21-43c4-b37e-4e6d38ecfc6b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;apply-form&quot;)/input[@id=&quot;query&quot;]</value>
      <webElementGuid>0e416bac-fe53-456e-abbd-f6155b550c93</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@id='query'])[2]</value>
      <webElementGuid>d3113a6c-fef9-4731-ad30-52faf3d8d734</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='apply-form']/input</value>
      <webElementGuid>55170d08-1649-45e6-87cb-d1d62242cdd5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/form/div/input</value>
      <webElementGuid>75adf033-ca81-47f1-a11f-75cacdf2c11b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'query' and @id = 'query' and @placeholder = 'Search clients by name, ssn, a-number, or phone number']</value>
      <webElementGuid>3cb61cdc-529a-4fea-8609-2e6979975388</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
