<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>p_members</name>
   <tag></tag>
   <elementGuidId>a51325a0-9e5c-4bfe-91b5-4320754ddf88</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//ol[@id='breadcrumb']/div/li[3]/div/a/div/p</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;members&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>c335f638-e8dc-4237-a87c-6d7be6094550</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>font-weight-bold text-capitalize</value>
      <webElementGuid>88cc2e15-2be7-49e4-b385-738f8a7f13c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>members</value>
      <webElementGuid>92118f9e-a60e-4601-aa4e-5911b98527f0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;breadcrumb&quot;)/div[@class=&quot;border d-flex flex-row p-2 rounded rounded-lg&quot;]/li[@class=&quot;brc-item breadcumb-link&quot;]/div[1]/a[@class=&quot;text-darker-grey&quot;]/div[@class=&quot;d-flex flex-row align-items-center&quot;]/p[@class=&quot;font-weight-bold text-capitalize&quot;]</value>
      <webElementGuid>7aaafdd0-bdb0-4b19-b98c-07b987a8c122</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ol[@id='breadcrumb']/div/li[3]/div/a/div/p</value>
      <webElementGuid>ea8be5ed-7936-4a47-b3e3-7f77dc089c23</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='BigBang Inc'])[1]/following::p[7]</value>
      <webElementGuid>1e4f0b1a-b2cb-472f-9033-a9a61f818a37</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Task'])[1]/preceding::p[2]</value>
      <webElementGuid>53fd471a-c9b5-47db-bbb1-4a6cf0ac5d19</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Comment'])[1]/preceding::p[2]</value>
      <webElementGuid>71a96e2f-c113-4fa4-879f-f32b097c584a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='members']/parent::*</value>
      <webElementGuid>81f3e919-14d4-45dd-8cce-0813396d0334</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[3]/div/a/div/p</value>
      <webElementGuid>a23afcf9-329a-4f91-a0a2-8316d969fe9e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[(text() = 'members' or . = 'members')]</value>
      <webElementGuid>67ce3dc1-e293-42b8-a78d-1f18ee6947e3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
