<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_Description_taskdescription</name>
   <tag></tag>
   <elementGuidId>9cf54463-651b-4479-bd90-918f5cb8fd0b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='task_description']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#task_description</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;Description (optional)&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>eaf7fdc6-6ef1-4cf9-a6e2-4c9a59224aa9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control text optional</value>
      <webElementGuid>b2261ad0-601d-4d40-8de8-ec6489ec5549</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Description (optional)</value>
      <webElementGuid>e730d276-835a-485b-97b9-d714669a7fce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>task[description]</value>
      <webElementGuid>a78ef603-d97b-4f9f-a2f0-f3d4fcd7c1ca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>task_description</value>
      <webElementGuid>9b9bc1c9-6cf0-4ab4-80b4-2d3a212cd9d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;task_description&quot;)</value>
      <webElementGuid>e793357f-5b0a-451d-842b-5466f61e1701</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='task_description']</value>
      <webElementGuid>15463b50-d30f-4629-aec3-0fc7a7e51c7b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='new_task']/div[2]/textarea</value>
      <webElementGuid>ac3d2906-09ac-4124-840a-4abfbe7f7fe6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//textarea</value>
      <webElementGuid>7db8d7fb-6be8-4eed-a94d-b1f8b562af30</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@placeholder = 'Description (optional)' and @name = 'task[description]' and @id = 'task_description']</value>
      <webElementGuid>ac796461-c550-4fab-9494-05472ab1b30e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
